/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    private static final String FRIDAY = "Friday";
    public static String isFriday(String day) {
        if(FRIDAY.equalsIgnoreCase(day)) {
            return "TGIF!";
        }
        return "Nope";
    }

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
