/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
public class UnitTest {

    @Mock
    private DayService dayService;


    @Test
    void givenDayMonday_thenIsNotFriday() {
        UnitTestApp unitTestApp = new UnitTestApp(dayService);
        String day = "Monday";
        String expectedResult = "Nope";
        assertEquals(expectedResult, unitTestApp.isFriday(day));
    }

    @Test
    void givenDayFriday_thenTGIF() {
        UnitTestApp unitTestApp = new UnitTestApp(dayService);
        String day = "Friday";
        String expectedResult = "TGIF!";
        assertEquals(expectedResult, unitTestApp.isFriday(day));
    }

    @Test
    void givenMockDayMonday_thenIsNotFriday() {
        UnitTestApp unitTestApp = new UnitTestApp(dayService);
        String expectedResult = "Nope";
        when(dayService.getDay()).thenReturn("Monday");
        assertEquals(expectedResult, unitTestApp.isFriday());
    }
    @Test
    void givenMockDayFriday_thenIsNotFriday() {
        UnitTestApp unitTestApp = new UnitTestApp(dayService);
        String expectedResult = "TGIF!";
        when(dayService.getDay()).thenReturn("Friday");
        assertEquals(expectedResult, unitTestApp.isFriday());
    }
}
